version: "3.9"
services:
  server:
    image: assentify-logo-detector-api
    build: ./server
    restart: always
    ports:
      - 5000:5000
    volumes:
      - ./server:/app
  web:
    image: assentify-logo-detector-web
    build: ./client
    restart: always
    ports:
      - 3000:3000
    volumes:
      - ./client:/app
    depends_on:
      - server
